=== universAAL/tools.eclipse-plugins/configuration-editor/universaalconfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
	<!--
		Authors: Tom Zentek, zentek@fzi.de
		Revised: 09.07.2013
	-->
<schema targetNamespace="http://universaal.cas.de" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:universaal="http://universaal.cas.de">


    <complexType name="Category">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="SPARQLConfigItem"
    			type="universaal:SPARQLConfigItem" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="MapConfigItem"
    			type="universaal:MapConfigItem" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="SimpleConfigItem"
    			type="universaal:SimpleConfigItem" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
            <element name="Dependencies" type="universaal:Dependency"
    			minOccurs="0">
    		</element>
    	</sequence>
    	
    	<attribute name="id" type="ID" use="required"></attribute>
    	<attribute name="label" type="string" use="required"></attribute>
    	<attribute name="description" type="string"></attribute>
    </complexType>

    <element name="configuration" type="universaal:Configuration"></element>

    <complexType name="SPARQLConfigItem">
    	<complexContent>
    		<extension base="universaal:ConfigItem">
    			<sequence>
    				<element name="query" type="string"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="MapConfigItem">
    	<complexContent>
    		<extension base="universaal:ConfigItem">
    			<sequence>
    				<element name="options" type="universaal:Options" minOccurs="1" maxOccurs="1"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="SimpleConfigItem">
    	<complexContent>
    		<extension base="universaal:ConfigItem">
    			<sequence>
    				<element name="defaultValue" type="string" minOccurs="0"></element>
    			</sequence>
    			<attribute name="type" use="required">
    				<simpleType>
    					<restriction base="string">
    						<pattern value="(string|int|double)"></pattern>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="ConfigItem">
    	<sequence>
    		<element name="label" type="string"></element>
    		<element name="description" type="string"></element>
    		<element name="dependencies" type="universaal:Dependency"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="validators" type="universaal:Validators"
    			minOccurs="0">
    		</element>
    		<element name="onConfigurationModelChangedListener" type="universaal:OnConfigurationModelChangedListener" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    	<attribute name="id" type="ID" use="required"></attribute>
    	<attribute name="active" type="boolean" use="optional"
    		default="true">
    	</attribute>
    	<attribute name="cardinality" use="optional" default="0..1">
    		<simpleType>
    			<restriction base="string">
    				<pattern value="[0-9]+..[0-9*]+"></pattern>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="Validator">
    	<sequence>
    		<element name="attribute" type="string" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="class" use="required">
    		<simpleType>
    			<restriction base="string">
    				<pattern value="[a-zA-Z.]*"></pattern>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>



    <complexType name="Configuration">
    	<sequence>
    		<element name="category" type="universaal:Category"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="id" type="ID" use="required"></attribute>
    	<attribute name="bundlename" type="string" use="required"></attribute>
    	<attribute name="version" use="required">
    		<simpleType>
    			<restriction base="string">
    				<pattern value="([0-9]+.{0,1})+[0-9]+"></pattern>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="author" type="string" use="required"></attribute>
    </complexType>

    <complexType name="Dependency">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="item" type="universaal:Item"></element>
    	</sequence>
    </complexType>

    <complexType name="Item">
    	<attribute name="id" use="required" type="IDREF">
    	</attribute>
    </complexType>





    <complexType name="Options">
    	<sequence>
    		<element name="option" type="universaal:Option" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="Option">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="key" type="int" use="required"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="Validators">
    	<sequence>
    		<element name="validator" type="universaal:Validator" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>


    <simpleType name="SimpleType">
    	<restriction base="string"></restriction>
    </simpleType>

    <simpleType name="Type">
    	<restriction base="string"></restriction>
    </simpleType>

    <complexType name="OnConfigurationModelChangedListener">
    	<attribute name="class">
    		<simpleType>
    			<restriction base="string">
    				<pattern value="[a-zA-Z.]*"></pattern>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>
</schema>

=== universAAL/tools.eclipse-plugins/configuration-editor/info.xml
<universaal:configuration xmlns:universaal="http://universaal.fzi.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" author="zentek" id="de.fzi.infoframe.configuration.first" bundlename="de.fzi.uc.infoframe" version="1.0.0" xsi:schemaLocation="http://universaal.fzi.de universaalconfiguration.xsd ">
  <universaal:category id="MainParameters" label="Main Parameters">
    <universaal:SimpleConfigItem cardinality="1..1" id="RSSUpdateTime" type="int">
      <universaal:label>RSS update time</universaal:label>
      <universaal:description>Please insert the RSS update time in seconds.</universaal:description>
      <universaal:validators>
        <universaal:validator class="de.fzi.merlin.aal.configuration.model.validators.RegExpValidator">
          <universaal:attribute>[0-9]*</universaal:attribute>
        </universaal:validator>
      </universaal:validators>
      <universaal:defaultValue>10</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem cardinality="1..1" id="ImageWidth" type="int">
      <universaal:label>Image width</universaal:label>
      <universaal:description>Please insert the with of the image</universaal:description>
      <universaal:validators>
        <universaal:validator class="">
          <universaal:attribute>100</universaal:attribute>
          <universaal:attribute>1080</universaal:attribute>
        </universaal:validator>
      </universaal:validators>
      <universaal:defaultValue>200</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem cardinality="1..1" id="ImageHeight" type="int">
      <universaal:label>Image height</universaal:label>
      <universaal:description>Please insert the height of the image</universaal:description>
      <universaal:validators>
        <universaal:validator class="">
          <universaal:attribute>100</universaal:attribute>
          <universaal:attribute>1920</universaal:attribute>
        </universaal:validator>
      </universaal:validators>
      <universaal:defaultValue>200</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:MapConfigItem cardinality="1..1" id="InfoFont">
      <universaal:label>The font</universaal:label>
      <universaal:description>Please choose your font.</universaal:description>
      <universaal:options>
        <universaal:option key="1">Arial</universaal:option>
        <universaal:option key="2">Tahoma</universaal:option>
        <universaal:option key="3">Calibri</universaal:option>
      </universaal:options>
    </universaal:MapConfigItem>
    <universaal:SimpleConfigItem cardinality="1..1" id="FontScale" type="double">
      <universaal:label>The font scale</universaal:label>
      <universaal:description>Please insert the font scale.</universaal:description>
      <universaal:validators>
        <universaal:validator class="">
          <universaal:attribute>0.1</universaal:attribute>
          <universaal:attribute>1</universaal:attribute>
        </universaal:validator>
      </universaal:validators>
      <universaal:defaultValue>1</universaal:defaultValue>
    </universaal:SimpleConfigItem>
  </universaal:category>
  <universaal:category label="Weather Plugin" id="WeatherPlugin">
    <universaal:SimpleConfigItem cardinality="1..1" id="WeatherStationLocation" type="string">
      <universaal:label>The weather station location</universaal:label>
      <universaal:description>Please insert the weather station location.</universaal:description>
      <universaal:defaultValue>Karlsruhe</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem cardinality="1..1" id="InterfaceLanguage" type="string">
      <universaal:label>The interface language</universaal:label>
      <universaal:description>Please insert the interface language.</universaal:description>
      <universaal:validators>
        <universaal:validator class="">
          <universaal:attribute>(language1|language2)</universaal:attribute>
        </universaal:validator>
      </universaal:validators>
      <universaal:defaultValue>de</universaal:defaultValue>
    </universaal:SimpleConfigItem>
  </universaal:category>
  <universaal:category label="Mail plugin" id="mailPlugin">
    <universaal:SimpleConfigItem id="addMailPlugin" cardinality="1..1" type="int">
      <universaal:label>On\\Off switch</universaal:label>
      <universaal:description>Switch the mail plugin on or off.</universaal:description>
      <universaal:onConfigurationModelChangedListener class="de.fzi.uc.infoframe.listeners.AddMailPluginListener" />
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem id="mailProtocol" cardinality="1..1" active="false" type="string">
      <universaal:label>Mail protocol</universaal:label>
      <universaal:description>Enter the mail protocol (like imap or pop3)</universaal:description>
      <universaal:defaultValue>imaps</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem id="mailServer" cardinality="1..1" type="string" active="false">
      <universaal:label>Mail server</universaal:label>
      <universaal:description>Enter the mail server url</universaal:description>
      <universaal:defaultValue>imap.gmail.com</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem id="mailUsername" cardinality="1..1" type="string" active="false">
      <universaal:label>E-Mail username</universaal:label>
      <universaal:description>Enter the username of your e-mail account.</universaal:description>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem id="mailPassword" cardinality="1..1" type="string" active="false">
      <universaal:label>E-Mail password</universaal:label>
      <universaal:description>Enter the password of your e-mail account.</universaal:description>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem id="mailMsgCount" cardinality="1..1" type="int" active="false">
      <universaal:label>Display meassage count.</universaal:label>
      <universaal:description>Enter the maximum amount of displayed messages.</universaal:description>
      <universaal:defaultValue>3</universaal:defaultValue>
    </universaal:SimpleConfigItem>
  </universaal:category>
  <universaal:category label="Calendar plugin" id="calendarPlugin">
    <universaal:SimpleConfigItem id="addCalendarPlugin" cardinality="1..1" type="int">
      <universaal:label>On\\Off switch</universaal:label>
      <universaal:description>Switch the calendar plugin on or off.</universaal:description>
      <universaal:onConfigurationModelChangedListener class="de.fzi.uc.infoframe.listeners.AddCalendarPluginListener" />
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem id="calendarUsername" cardinality="1..1" type="string" active="false">
      <universaal:label>Calendar username</universaal:label>
      <universaal:description>Enter the username of your google calendar account.</universaal:description>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem id="calendarPassword" cardinality="1..1" type="string" active="false">
      <universaal:label>Calendar password</universaal:label>
      <universaal:description>Enter the password of your google calendar account.</universaal:description>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem id="calendarMsgCount" cardinality="1..1" type="int" active="false">
      <universaal:label>Display event count.</universaal:label>
      <universaal:description>Enter the maximum amount of displayed events.</universaal:description>
      <universaal:defaultValue>3</universaal:defaultValue>
    </universaal:SimpleConfigItem>
  </universaal:category>
  <universaal:category label="Feed Plugin" id="FeedPlugin">
    <universaal:SimpleConfigItem cardinality="1..1" id="AddFeedPlugin" type="int">
      <universaal:label>On\\Off switch</universaal:label>
      <universaal:description>Switches plugin on\\off</universaal:description>
      <universaal:validators>
        <universaal:validator class="">
          <universaal:attribute>0</universaal:attribute>
          <universaal:attribute>1</universaal:attribute>
        </universaal:validator>
      </universaal:validators>
      <universaal:onConfigurationModelChangedListener class="de.fzi.uc.infoframe.listeners.ModListener" />
      <universaal:defaultValue>0</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem cardinality="0..1" id="FeedURL1" type="string" active="false">
      <universaal:label>The first feed url</universaal:label>
      <universaal:description>Please insert the first feed url.</universaal:description>
      <universaal:validators>
        <universaal:validator class="de.cas.uc.infoframe.validation.URLValidator" />
      </universaal:validators>
      <universaal:defaultValue>http://google.de</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem cardinality="0..1" id="MaxDispItems1" type="int" active="false">
      <universaal:label>Count of displayed feed items</universaal:label>
      <universaal:description>Maximum numbers of entries to display</universaal:description>
      <universaal:dependencies>
        <universaal:item id="FeedURL1" />
      </universaal:dependencies>
      <universaal:validators>
        <universaal:validator class="">
          <universaal:attribute>1</universaal:attribute>
          <universaal:attribute>10</universaal:attribute>
        </universaal:validator>
      </universaal:validators>
      <universaal:defaultValue>5</universaal:defaultValue>
    </universaal:SimpleConfigItem>
    <universaal:SimpleConfigItem cardinality="0..1" id="RegExp1" type="string" active="false">
      <universaal:label>The regular expression</universaal:label>
      <universaal:description>Regular expression for feed 1</universaal:description>
      <universaal:dependencies>
